name: Update

on:
  schedule:
    - cron: '0 5 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update beam
      run: nix run github:akirak/flake-templates#update-beam
      continue-on-error: true
      id: update

    - uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 'Update Erlang'
        # token: ${{ secrets.PAT_FOR_PR }}
        base: master
        title: 'chore: Update Erlang'
        branch: create-pull-request/update
        labels: automation,update
